import { createHash } from "node:crypto";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { Database } from "bun:sqlite";
import { reconcileComments } from "./anchors";
import type { GitBackend } from "./git-backend";
import { ghCreatePr, ghPrClose, ghPrComment } from "./github";
import { buildSlicePatch, materializeSliceCommits } from "./materialize";
import type { Hunk, PlanResult } from "./planner";
import { deleteCorrespondence, getCorrespondence, upsertCorrespondence } from "./store";

// See docs/adr/0006-slice-correspondence-key.md.
export function computeSliceSignature(hunks: Hunk[]): string {
  const parts = hunks.map((h) => `${h.file}::${h.qualifiedSymbol ?? "?"}`).sort();
  return createHash("sha1").update(parts.join("|")).digest("hex").slice(0, 12);
}

// M3: content hash of the slice's actual patch text — distinct from the
// symbol-signature above. Unchanged hash across runs means the diff itself
// didn't change, so the branch/PR don't need touching.
function computeContentHash(patch: string): string {
  return createHash("sha1").update(patch).digest("hex").slice(0, 12);
}

export type PushResult = {
  sliceLabel: string;
  branchName: string;
  prUrl: string | null;
  status: "created" | "updated" | "unchanged" | "squash-merged" | "dry-run";
};

export async function push(opts: {
  git: GitBackend;
  db: Database;
  repoRoot: string;
  branch: string;
  baseBranch: string;
  mergeBase: string;
  plan: PlanResult;
  dryRun: boolean;
}): Promise<PushResult[]> {
  const { git, db, repoRoot, branch, baseBranch, mergeBase, plan, dryRun } = opts;
  const commits = await materializeSliceCommits({ git, repoRoot, mergeBase, files: plan.files, order: plan.order!, slices: plan.slices });

  // Squash-merge check: does this slice's patch already exist in baseBranch's
  // current tip? A clean --reverse --check apply means yes. One scratch index,
  // rebuilt fresh per slice from the tip (--check never mutates it, but
  // read-tree is cheap and keeps each check independent of the others).
  const baseTip = git.revParse(baseBranch, repoRoot);
  const tmpDir = mkdtempSync(join(tmpdir(), "drip-reconcile-"));
  const indexFile = join(tmpDir, "index");
  const scratchEnv = { ...process.env, GIT_INDEX_FILE: indexFile };

  const results: PushResult[] = [];
  let baseForNext = baseBranch;

  try {
    for (const { sliceId, commit } of commits) {
      const sliceLabel = `slice${plan.idToNum.get(sliceId)}`;
      const branchName = `drip/${branch}/${sliceLabel}`;
      const hunks = plan.slices.get(sliceId)!;
      const signature = computeSliceSignature(hunks);
      const patch = buildSlicePatch(plan.files, plan.slices, sliceId);
      const contentHash = computeContentHash(patch);
      const existing = getCorrespondence(db, branch, signature);

      let squashMerged = false;
      if (patch) {
        git.readTree(baseTip, repoRoot, scratchEnv);
        const patchFile = join(tmpDir, "check.diff");
        writeFileSync(patchFile, patch);
        squashMerged = git.applyCachedReverseCheck(patchFile, repoRoot, scratchEnv);
      }

      if (dryRun) {
        const status = squashMerged ? "squash-merged" : existing?.contentHash === contentHash ? "unchanged" : "dry-run";
        results.push({ sliceLabel, branchName, prUrl: existing?.prUrl ?? null, status });
        if (!squashMerged) baseForNext = branchName;
        continue;
      }

      if (squashMerged) {
        if (existing?.prNumber) {
          ghPrClose(repoRoot, existing.prNumber, "Closed by drip: this slice's content is already present on the base branch (squash-merge detected).");
          deleteCorrespondence(db, branch, signature);
        }
        results.push({ sliceLabel, branchName, prUrl: existing?.prUrl ?? null, status: "squash-merged" });
        continue; // dropped from the stack — baseForNext stays where it was
      }

      if (existing && existing.contentHash === contentHash) {
        results.push({ sliceLabel, branchName, prUrl: existing.prUrl, status: "unchanged" });
        baseForNext = branchName;
        continue;
      }

      git.push("origin", `${commit}:refs/heads/${branchName}`, repoRoot, true);

      let prUrl = existing?.prUrl ?? null;
      let prNumber = existing?.prNumber ?? null;

      if (!existing) {
        const files = [...new Set(hunks.map((h) => h.file))];
        const title = `drip: ${sliceLabel} — ${files[0]}${files.length > 1 ? ` +${files.length - 1} more` : ""}`;
        const body = [`Auto-generated by \`drip push\` for mega branch \`${branch}\`.`, "", "Files touched:", ...files.map((f) => `- ${f}`)].join(
          "\n",
        );
        const pr = ghCreatePr({ repoRoot, base: baseForNext, head: branchName, title, body });
        prUrl = pr.url;
        prNumber = pr.number;
      } else if (existing.commitSha && existing.contentHash && existing.contentHash !== contentHash && prNumber) {
        // Content changed under an existing PR — GitHub won't render a
        // force-push diff natively, so post the interdiff as a comment.
        const interdiff = git.diff(existing.commitSha, commit, repoRoot);
        if (interdiff.trim()) {
          const body = ["Interdiff (previous force-push → this one):", "", "```diff", interdiff.slice(0, 60000), "```"].join("\n");
          ghPrComment(repoRoot, prNumber, body);
        }
        // M4: relocate/orphan review comments anchored to hunks this push changed.
        await reconcileComments({ git, db, repoRoot, branch, sliceSignature: signature, mergeBase, oldCommitSha: existing.commitSha, newHunks: hunks, prNumber });
      }

      upsertCorrespondence(db, { branch, sliceSignature: signature, sliceBranch: branchName, prNumber, prUrl, contentHash, commitSha: commit });
      results.push({ sliceLabel, branchName, prUrl, status: existing ? "updated" : "created" });
      baseForNext = branchName;
    }
  } finally {
    rmSync(tmpDir, { recursive: true, force: true });
  }

  return results;
}
