import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { Database } from "bun:sqlite";
import { reconcileComments } from "./anchors";
import type { GitBackend } from "./git-backend";
import { ghCreatePr, ghPrClose, ghPrComment, ghPrSetBase } from "./github";
import { buildSlicePatch, materializeFlatFirst, materializeSliceCommits, type FlatFirstSlice, type ProjectionMode } from "./materialize";
import type { Hunk, PlanResult } from "./planner";
import { unitBranchName } from "./refs";
import { computeContentHash, computeSliceSignature } from "./signature";
import { deleteCorrespondence, getCorrespondence, upsertCorrespondence, type Correspondence } from "./store";

// "blocked" means there was nothing safe to push and drip said so instead of
// skipping quietly: the slice's hunks wouldn't apply on its prerequisites
// alone (flat-first), or the branch moved on the remote since drip last wrote
// it (docs/adr/0020 for adopted branches, docs/adr/0028 for drip-owned ones).
export type SliceStatus = "created" | "updated" | "unchanged" | "squash-merged" | "dry-run" | "blocked";


export type PushResult = {
  sliceLabel: string;
  branchName: string;
  prUrl: string | null;
  /** the PR this unit corresponds to — what a GitHub stack is built out of (docs/adr/0030) */
  prNumber: number | null;
  status: SliceStatus;
  base: string; // the ref this slice's PR targets
  note: string | null; // why it's blocked, or that a generated integration base was used
  /**
   * The draft state this run *sets*, which only ever happens when drip opens
   * the PR: true = opened as a draft, false = opened ready for review, null =
   * no PR is being opened, so whatever state the PR already has is left alone.
   * Reported in dry-run too — "would open five drafts" is exactly the thing a
   * preview has to say before `--yes`.
   */
  draft: boolean | null;
  /**
   * True when this PR targets a *generated* integration branch — one drip
   * minted to union several prerequisites, which has no PR of its own. The PR
   * merges, but its prerequisites aren't reviewable as a stack and a workflow
   * filtered on `pull_request.branches: [main]` never runs on it (issue #14).
   */
  hiddenBase: boolean;
};

// Pure: which of the five statuses a slice is in, given what's already known
// about it. No I/O, no GitBackend -- the whole point of pulling this out of
// push()'s loop is that this five-way decision is unit-testable on its own.
//
// Priority is squash-merged > unchanged > (dry-run ? "dry-run" : created/updated)
// in both dry-run and real mode -- dry-run only changes whether the final
// bucket reports "dry-run" instead of the real created/updated split.
export function classifySliceStatus(opts: {
  existing: Correspondence | null;
  squashMerged: boolean;
  contentHash: string;
  dryRun: boolean;
}): SliceStatus {
  const { existing, squashMerged, contentHash, dryRun } = opts;
  if (squashMerged) return "squash-merged";
  if (existing && existing.contentHash === contentHash) return "unchanged";
  if (dryRun) return "dry-run";
  return existing ? "updated" : "created";
}

// What push actually iterates over. Atomic slices by default; a manifest's
// semantic projections when one is supplied (issue #9). Keeping this one shape
// is what lets both go through the same squash-merge, correspondence,
// interdiff and comment-reconciliation path instead of a parallel code path.
export type PushUnits = {
  order: string[];
  slices: Map<string, Hunk[]>;
  edges: [string, string][];
  label: (id: string) => string;
  /** durable correspondence identity — see docs/adr/0018 */
  signature: (id: string) => string;
  title: (id: string) => string;
  body: (id: string) => string;
};

export function unitsFromPlan(plan: PlanResult, branch: string): PushUnits {
  const label = (id: string) => `slice${plan.idToNum.get(id)}`;
  return {
    order: plan.order!,
    slices: plan.slices,
    edges: plan.edges,
    label,
    signature: (id) => computeSliceSignature(plan.slices.get(id)!),
    title: (id) => {
      const files = [...new Set(plan.slices.get(id)!.map((h) => h.file))];
      return `drip: ${label(id)} — ${files[0]}${files.length > 1 ? ` +${files.length - 1} more` : ""}`;
    },
    body: (id) => {
      const files = [...new Set(plan.slices.get(id)!.map((h) => h.file))];
      return [`Auto-generated by \`drip push\` for mega branch \`${branch}\`.`, "", "Files touched:", ...files.map((f) => `- ${f}`)].join("\n");
    },
  };
}

export async function push(opts: {
  git: GitBackend;
  db: Database;
  repoRoot: string;
  branch: string;
  baseBranch: string;
  mergeBase: string;
  plan: PlanResult;
  dryRun: boolean;
  projection?: ProjectionMode;
  units?: PushUnits;
  /** open drip-owned PRs as drafts; never changes an existing PR's state */
  draft?: boolean;
  /** refuse any projection that would need a generated integration base (issue #14) */
  reviewableStack?: boolean;
  /**
   * Push over a *drip-owned* branch that has moved on the remote, instead of
   * refusing it. Never applies to an adopted branch — drip doesn't own that one
   * and no flag here makes it safe to discard someone else's commit
   * (docs/adr/0028).
   */
  reclaim?: boolean;
}): Promise<PushResult[]> {
  const { git, db, repoRoot, branch, baseBranch, mergeBase, plan, dryRun } = opts;
  const projection = opts.projection ?? "stacked";
  const units = opts.units ?? unitsFromPlan(plan, branch);
  const label = units.label;

  // Memoized only: the rule itself is unitBranchName's (src/refs.ts). A
  // dependent's base is resolved through here too, so the lookup happens
  // several times per unit in a stack.
  const branchCache = new Map<string, string>();
  const sliceBranch = (id: string) => {
    let name = branchCache.get(id);
    if (name === undefined) {
      name = unitBranchName(db, branch, units.signature(id), label(id));
      branchCache.set(id, name);
    }
    return name;
  };
  const treeOf = (commitish: string): string | null => {
    try {
      return git.revParse(`${commitish}^{tree}`, repoRoot);
    } catch {
      return null;
    }
  };

  // Both modes materialize the same slice content; they differ only in what
  // each slice's branch is built on, and therefore what its PR can target.
  const flatById = new Map<string, FlatFirstSlice>();
  let commits: Array<{ sliceId: string; commit: string | null }>;
  if (projection === "flat-first") {
    const flat = await materializeFlatFirst({
      git,
      repoRoot,
      mergeBase,
      files: plan.files,
      order: units.order,
      slices: units.slices,
      edges: units.edges,
      label,
    });
    for (const f of flat) flatById.set(f.sliceId, f);
    commits = flat;
  } else {
    commits = await materializeSliceCommits({ git, repoRoot, mergeBase, files: plan.files, order: units.order, slices: units.slices });
  }

  // Squash-merge check: does this slice's patch already exist in baseBranch's
  // current tip? A clean --reverse --check apply means yes. One scratch index,
  // rebuilt fresh per slice from the tip (--check never mutates it, but
  // read-tree is cheap and keeps each check independent of the others).
  // What the remote actually holds right now, read once for the whole run.
  // Without this, "unchanged" means "drip's materialized tree matches the one
  // drip recorded last time" and says nothing about the branch a reviewer is
  // looking at: a commit pushed onto a drip-owned branch made the PR disagree
  // with the projection, and drip either force-pushed over it or reported
  // `unchanged` and left it there. Sha comparison against the recorded
  // correspondence closes both holes (docs/adr/0028).
  //
  // A real push needs the network anyway, so a failure here is fatal — silently
  // skipping the check immediately before a force-push is the bug being fixed.
  // A dry-run is expected to work offline, so there it degrades to "unknown"
  // and every affected result says the check didn't run.
  let remoteHeads: Map<string, string> | null;
  try {
    remoteHeads = git.lsRemoteHeads("origin", repoRoot);
  } catch (e) {
    if (!dryRun) throw e;
    remoteHeads = null;
  }

  const baseTip = git.revParse(baseBranch, repoRoot);
  const tmpDir = mkdtempSync(join(tmpdir(), "drip-reconcile-"));
  const indexFile = join(tmpDir, "index");
  const scratchEnv = { ...process.env, GIT_INDEX_FILE: indexFile };

  const results: PushResult[] = [];
  let baseForNext = baseBranch;
  // Slices whose content already landed on the base branch: a flat-first
  // dependent must target the base branch itself rather than a branch that
  // was dropped from this run.
  const droppedToBase = new Set<string>();
  // Slices this run refused to push. A dependent of one of them would open a
  // PR against a branch that doesn't exist, so it's refused too rather than
  // left to fail at GitHub.
  const blockedIds = new Set<string>();

  try {
    for (const { sliceId, commit } of commits) {
      const sliceLabel = label(sliceId);
      const branchName = sliceBranch(sliceId);
      const hunks = units.slices.get(sliceId)!;
      const signature = units.signature(sliceId);
      const patch = buildSlicePatch(plan.files, units.slices, sliceId);
      const existing = getCorrespondence(db, branch, signature);
      const flat = flatById.get(sliceId);

      // Every refusal below produces the same shape: nothing pushed, the slice
      // recorded as blocked so its dependents are refused too.
      const block = (note: string): void => {
        blockedIds.add(sliceId);
        results.push({ sliceLabel, branchName, prUrl: existing?.prUrl ?? null, prNumber: existing?.prNumber ?? null, status: "blocked", base: baseBranch, note, draft: null, hiddenBase: false });
      };

      if (!commit) {
        block(`${flat?.applyError ?? "could not be materialized"} — re-run with --projection stacked to include this slice`);
        continue;
      }

      const blockedPrereq = flat?.prerequisites.find((p) => blockedIds.has(p));
      if (blockedPrereq) {
        block(`its prerequisite ${label(blockedPrereq)} was not pushed, so this PR would target a branch that doesn't exist`);
        continue;
      }

      // Draft is a property of *opening* a PR. An existing one — drip's own or
      // an adopted human's — keeps whatever state it has: there is no `gh pr
      // edit --draft`, and "someone marked this ready for review" is a review
      // decision, not something a re-run should undo.
      let draft: boolean | null = existing ? null : !!opts.draft;

      // The chosen base. Stacked: whatever the previous surviving slice was.
      // Flat-first: the base branch for a root, the single prerequisite's
      // branch, or a generated integration branch unioning several.
      let integrationBranch: string | null = null;
      let base: string;
      let note: string | null = null;
      if (projection === "stacked") {
        base = baseForNext;
      } else if (flat!.integrationCommit) {
        // A generated integration base is mergeable and not reviewable: it has
        // no PR, so reviewers can't see the prerequisites as a stack, and a
        // workflow filtered on the base branch never fires. Say so on every
        // run, and refuse outright when the caller asked for a stack that a
        // human can actually walk (issue #14).
        if (opts.reviewableStack) {
          block(
            `needs a generated integration base unioning ${flat!.prerequisites.map(label).join(", ")}, which would have no PR of its own — ` +
              "--reviewable-stack refuses that. Merge those prerequisites into one projection, or declare a projection that depends on them " +
              "and let this one depend on it instead.",
          );
          continue;
        }
        integrationBranch = `${branchName}-base`;
        base = integrationBranch;
        note =
          `integration base unions ${flat!.prerequisites.map(label).join(", ")} — '${integrationBranch}' is generated and has no PR, ` +
          "so these prerequisites are not directly reviewable on GitHub and a workflow filtered on the base branch won't run CI here";
      } else if (flat!.baseSliceId && !droppedToBase.has(flat!.baseSliceId)) {
        base = sliceBranch(flat!.baseSliceId);
      } else {
        base = baseBranch;
      }
      // Only meaningful for a PR this run leaves pointing at the generated
      // branch — a squash-merged slice's PR is closed, so it targets nothing.
      let hiddenBase = !!integrationBranch;

      if (flat?.widened) {
        note = [note, `prerequisites widened past the slice DAG to make the patch apply: ${flat.prerequisites.map(label).join(", ")}`]
          .filter(Boolean)
          .join("; ");
      }

      // What this slice's PR would actually show: the tree its branch resolves
      // to, plus the ref it targets. Hashing only the slice's own patch would
      // call a slice "unchanged" — and skip the force-push — when the branch
      // content underneath it moved (an earlier slice edited in stacked mode,
      // or a projection switch changing what the branch is built on). The
      // materialized commit's sha is not usable here: `commit-tree` mints a
      // fresh sha every run, its tree doesn't.
      const contentHash = computeContentHash([patch, git.revParse(`${commit}^{tree}`, repoRoot), base].join("\n--drip--\n"));

      let squashMerged = false;
      if (patch) {
        git.readTree(baseTip, repoRoot, scratchEnv);
        const patchFile = join(tmpDir, "check.diff");
        writeFileSync(patchFile, patch);
        squashMerged = git.applyCachedReverseCheck(patchFile, repoRoot, scratchEnv);
      }

      // An adopted branch is someone else's history. "The branch already shows
      // exactly this tree" is the right skip condition there, rather than the
      // content hash alone: the hash also moves when the *chosen base string*
      // does, and rewriting a reviewer-visible branch to change nothing but
      // its commit graph is pure loss (docs/adr/0020).
      const atThisTree = !!existing?.adopted && !!existing.commitSha && treeOf(existing.commitSha) === treeOf(commit);
      const effectiveHash = atThisTree && existing!.contentHash ? existing!.contentHash : contentHash;
      let status = classifySliceStatus({ existing, squashMerged, contentHash: effectiveHash, dryRun });

      // Asked for drafts and there's nothing to open: say so rather than let
      // the flag look like it did something.
      if (opts.draft && existing?.prNumber && status !== "squash-merged") {
        note = [
          note,
          `--draft applies only when opening a PR; ${existing.adopted ? "adopted " : ""}#${existing.prNumber} already exists and keeps its current draft/ready state`,
        ]
          .filter(Boolean)
          .join("; ");
      }
      if (status === "squash-merged") {
        draft = null;
        hiddenBase = false;
      }

      // Has the branch moved since drip last wrote it? Only meaningful once
      // there's a recorded sha to expect — a branch with no correspondence is
      // one drip has never pushed, and the name is drip's to claim.
      //
      // Deliberately checked after the squash-merge decision: a squash-merged
      // projection's branch is about to become irrelevant and its PR closed, so
      // whatever happened to it doesn't stand in the way of that cleanup.
      //
      // The rule across both cases below: discarding a commit drip didn't write
      // needs permission, recreating drip's own branch doesn't.
      let leaseExpect: string | null = existing?.commitSha ?? null;
      if (status !== "squash-merged" && existing?.commitSha) {
        const remoteTip = remoteHeads?.get(branchName) ?? null;
        // Whatever the remote says, "unchanged" was decided against the sha
        // drip recorded, not against the branch as it stands now.
        const mustRepush = () => {
          if (status === "unchanged") status = dryRun ? "dry-run" : "updated";
        };

        if (remoteHeads === null) {
          note = [note, "could not read the remote to check whether this branch has moved; a real push checks this and refuses on drift"]
            .filter(Boolean)
            .join("; ");
        } else if (remoteTip && remoteTip !== existing.commitSha) {
          const moved =
            `${existing.adopted ? "the adopted branch" : "this branch"} is at ${remoteTip.slice(0, 7)} on the remote, ` +
            `but drip last wrote ${existing.commitSha.slice(0, 7)} — someone pushed to it`;
          if (existing.adopted) {
            block(`${moved}. Review those commits, then re-run \`drip manifest adopt\` to re-bind.`);
            continue;
          }
          if (!opts.reclaim) {
            block(
              `${moved}. Refusing rather than discarding it: fold the change into the mega branch and replan, ` +
                "or re-run with --reclaim to overwrite the branch with drip's projection.",
            );
            continue;
          }
          note = [note, `${moved}; --reclaim overwrote it`].filter(Boolean).join("; ");
          leaseExpect = remoteTip; // the recorded sha is stale; expect what's actually there
          mustRepush();
        } else if (!remoteTip) {
          // The branch is gone but correspondence still points at it. Putting
          // back a branch drip owns discards nothing, so it needs no flag; an
          // adopted branch drip never created is not one it will recreate.
          if (existing.adopted) {
            block(
              `the adopted branch ${branchName} no longer exists on the remote, but correspondence still records ` +
                `${existing.commitSha.slice(0, 7)}. Restore it, or drop the binding with \`drip manifest forget\`.`,
            );
            continue;
          }
          note = [note, `${branchName} was missing on the remote and was recreated from drip's projection`].filter(Boolean).join("; ");
          leaseExpect = null; // nothing to expect: the ref doesn't exist
          mustRepush();
        }
      }

      if (dryRun) {
        results.push({ sliceLabel, branchName, prUrl: existing?.prUrl ?? null, prNumber: existing?.prNumber ?? null, status, base, note, draft, hiddenBase });
        if (status !== "squash-merged") baseForNext = branchName;
        else droppedToBase.add(sliceId);
        continue;
      }

      if (status === "squash-merged") {
        if (existing?.prNumber) {
          ghPrClose(repoRoot, existing.prNumber, "Closed by drip: this slice's content is already present on the base branch (squash-merge detected).");
          deleteCorrespondence(db, branch, signature);
        }
        droppedToBase.add(sliceId);
        results.push({ sliceLabel, branchName, prUrl: existing?.prUrl ?? null, prNumber: existing?.prNumber ?? null, status, base, note, draft, hiddenBase });
        continue; // dropped from the stack — baseForNext stays where it was
      }

      if (status === "unchanged") {
        // Nothing to do: the hash above already covers the branch's tree and
        // its target ref, so "unchanged" really means the PR is already right.
        results.push({ sliceLabel, branchName, prUrl: existing!.prUrl, prNumber: existing!.prNumber, status, base, note, draft, hiddenBase });
        baseForNext = branchName;
        continue;
      }

      // status is "created" or "updated"
      if (integrationBranch && flat!.integrationCommit) {
        git.push("origin", `${flat!.integrationCommit}:refs/heads/${integrationBranch}`, repoRoot, true);
      }
      // Every branch drip has a recorded sha for is pushed under a lease, its
      // own included: the ls-remote check above reads the remote once per run,
      // and this is what closes the window between that read and this push.
      const lease = leaseExpect ? { ref: branchName, expect: leaseExpect } : undefined;
      try {
        git.push("origin", `${commit}:refs/heads/${branchName}`, repoRoot, true, lease);
      } catch (e) {
        if (!lease) throw e;
        // The lease did its job: the branch moved between this run's ls-remote
        // and this push. Refusing loudly and leaving that commit alone is the
        // whole point — for an adopted branch because drip doesn't own it, for
        // a drip-owned one because nobody asked for it to be discarded.
        blockedIds.add(sliceId);
        results.push({
          sliceLabel,
          branchName,
          prUrl: existing?.prUrl ?? null,
          prNumber: existing?.prNumber ?? null,
          status: "blocked",
          base,
          note:
            `${branchName} moved on the remote during this run (expected ${lease.expect.slice(0, 7)}) — ` +
            "force-with-lease refused rather than discard those commits. Re-run to see where it stands now.",
          draft: null,
          hiddenBase: false,
        });
        continue;
      }

      let prUrl = existing?.prUrl ?? null;
      let prNumber = existing?.prNumber ?? null;

      if (!existing) {
        const pr = ghCreatePr({ repoRoot, base, head: branchName, title: units.title(sliceId), body: units.body(sliceId), draft: !!opts.draft });
        prUrl = pr.url;
        prNumber = pr.number;
      } else if (existing.commitSha && existing.contentHash && existing.contentHash !== contentHash && prNumber) {
        // Content changed under an existing PR — GitHub won't render a
        // force-push diff natively, so post the interdiff as a comment.
        const interdiff = git.diff(existing.commitSha, commit, repoRoot);
        if (interdiff.trim()) {
          const body = ["Interdiff (previous force-push → this one):", "", "```diff", interdiff.slice(0, 60000), "```"].join("\n");
          ghPrComment(repoRoot, prNumber, body);
        }
        // M4: relocate/orphan review comments anchored to hunks this push changed.
        await reconcileComments({ git, db, repoRoot, branch, sliceSignature: signature, mergeBase, oldCommitSha: existing.commitSha, newHunks: hunks, prNumber });
      }

      // Retargeting is drip's to do on a PR it opened. On an adopted one the
      // base is a review decision someone else made, so a disagreement with
      // the manifest graph is reported and left alone — changing it is an
      // explicit act (change it on the PR, then re-run `manifest adopt`).
      let baseRef = base;
      if (existing?.prNumber && existing.baseRef && existing.baseRef !== base) {
        if (existing.adopted) {
          baseRef = existing.baseRef;
          note = [note, `PR #${existing.prNumber} targets ${existing.baseRef}, but the manifest implies ${base} — drip does not retarget an adopted PR`]
            .filter(Boolean)
            .join("; ");
        } else {
          ghPrSetBase(repoRoot, existing.prNumber, base);
        }
      }

      upsertCorrespondence(db, {
        branch,
        sliceSignature: signature,
        sliceBranch: branchName,
        prNumber,
        prUrl,
        contentHash,
        commitSha: commit,
        baseRef,
        adopted: !!existing?.adopted,
      });
      results.push({ sliceLabel, branchName, prUrl, prNumber, status, base, note, draft, hiddenBase });
      baseForNext = branchName;
    }
  } finally {
    rmSync(tmpDir, { recursive: true, force: true });
  }

  return results;
}
