import { createHash } from "node:crypto";
import type { Database } from "bun:sqlite";
import type { GitBackend } from "./git-backend";
import { ghCreatePr } from "./github";
import { materializeSliceCommits } from "./materialize";
import type { Hunk, PlanResult } from "./planner";
import { getCorrespondence, upsertCorrespondence } from "./store";

// See docs/adr/0006-slice-correspondence-key.md.
export function computeSliceSignature(hunks: Hunk[]): string {
  const parts = hunks.map((h) => `${h.file}::${h.qualifiedSymbol ?? "?"}`).sort();
  return createHash("sha1").update(parts.join("|")).digest("hex").slice(0, 12);
}

export type PushResult = { sliceLabel: string; branchName: string; prUrl: string | null; status: "created" | "updated" | "dry-run" };

export async function push(opts: {
  git: GitBackend;
  db: Database;
  repoRoot: string;
  branch: string;
  baseBranch: string;
  mergeBase: string;
  plan: PlanResult;
  dryRun: boolean;
}): Promise<PushResult[]> {
  const { git, db, repoRoot, branch, baseBranch, mergeBase, plan, dryRun } = opts;
  const commits = await materializeSliceCommits({ git, repoRoot, mergeBase, files: plan.files, order: plan.order!, slices: plan.slices });

  const results: PushResult[] = [];
  let baseForNext = baseBranch;

  for (const { sliceId, commit } of commits) {
    const sliceLabel = `slice${plan.idToNum.get(sliceId)}`;
    const branchName = `drip/${branch}/${sliceLabel}`;
    const hunks = plan.slices.get(sliceId)!;
    const signature = computeSliceSignature(hunks);
    const existing = getCorrespondence(db, branch, signature);

    if (dryRun) {
      results.push({ sliceLabel, branchName, prUrl: existing?.prUrl ?? null, status: "dry-run" });
      baseForNext = branchName;
      continue;
    }

    // Always (re-)push the branch — cheap, and covers content drift that the
    // symbol-signature key alone wouldn't catch (same symbols, edited lines).
    git.push("origin", `${commit}:refs/heads/${branchName}`, repoRoot, true);

    let prUrl = existing?.prUrl ?? null;
    let prNumber = existing?.prNumber ?? null;

    if (!existing) {
      const files = [...new Set(hunks.map((h) => h.file))];
      const title = `drip: ${sliceLabel} — ${files[0]}${files.length > 1 ? ` +${files.length - 1} more` : ""}`;
      const body = [`Auto-generated by \`drip push\` for mega branch \`${branch}\`.`, "", "Files touched:", ...files.map((f) => `- ${f}`)].join(
        "\n",
      );
      const pr = ghCreatePr({ repoRoot, base: baseForNext, head: branchName, title, body });
      prUrl = pr.url;
      prNumber = pr.number;
    }

    upsertCorrespondence(db, { branch, sliceSignature: signature, sliceBranch: branchName, prNumber, prUrl });
    results.push({ sliceLabel, branchName, prUrl, status: existing ? "updated" : "created" });
    baseForNext = branchName;
  }

  return results;
}
